const nodemailer = require("nodemailer");
require("dotenv").config();

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  family: 4, // Strictly force IPv4 socket (prevents ENETUNREACH on cloud containers)
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
  tls: {
    rejectUnauthorized: false,
  },
});

/**
 * Send email utility
 * @param {string} to - Recipient email
 * @param {string} subject - Email subject
 * @param {string} html - HTML content
 * @param {string} replyTo - Optional reply-to email
 * @param {string} cc - Optional CC email
 * @param {string|string[]} deliveryTo - Optional envelope recipient(s) override for security
 */
const sendEmail = async (to, subject, html, replyTo = null, cc = null, deliveryTo = null) => {
  try {
    const mailOptions = {
      from: process.env.EMAIL_FROM || (process.env.EMAIL_USER ? `DSMS <${process.env.EMAIL_USER}>` : "DSMS <noreply@DSMS.com>"),
      to,
      subject,
      html,
    };

    if (replyTo) mailOptions.replyTo = replyTo;
    
    // Set CC as a MIME header so Gmail UI shows CC under "to:"
    if (cc) {
      mailOptions.headers = {
        'Cc': cc
      };
    }

    if (deliveryTo) {
      mailOptions.envelope = {
        from: process.env.EMAIL_USER || mailOptions.from,
        to: Array.isArray(deliveryTo) ? deliveryTo : [deliveryTo]
      };
    }

    const info = await transporter.sendMail(mailOptions);
    console.log("Email sent: " + info.response);
    return true;
  } catch (error) {
    console.error("Email sending failed:", error.message);
    return false;
  }
};

/**
 * Templates
 */
const templates = {
  documentAssigned: (userName, docTitle, docId, customMessage = null, customLink = null, ccList = null) => {
    const frontendBaseUrl = process.env.FRONTEND_URL || 'https://dsms-web-app-bay.vercel.app';
    const link = customLink || `${frontendBaseUrl}/sign/${docId}`;
    return `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #0e9e8a;">DSMS</h1>
            </div>
            <p>Hi <b>${userName}</b>,</p>
            <p>You have been assigned a new document to sign: <b>${docTitle}</b>.</p>
            
            ${
              ccList
                ? `<p style="font-size: 13px; color: #475569; margin: 15px 0;"><b>CC:</b> ${ccList}</p>`
                : ""
            }

                ${
                  customMessage
                    ? `
            <div style="background-color: #f8fafc; border-left: 4px solid #0e9e8a; padding: 15px; margin: 20px 0;">
                <p style="margin: 0; font-style: italic; color: #475569;">"${customMessage}"</p>
                </div>
                `
                    : ""
                }

            <div style="text-align: center; margin: 30px 0;">
                <a href="${link}" style="background-color: #0e9e8a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">Sign Document</a>
            </div>
            <p style="font-size: 12px; color: #64748b;">If the button doesn't work, copy this link: ${link}</p>
        </div>
    `;
  },
  documentCCNotification: (userName, docTitle, docId, customMessage = null, ccList = null) => {
    return `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #0e9e8a;">DSMS</h1>
            </div>
            <p>Hi <b>${userName}</b>,</p>
            <p>You have been CC'd as an observer on a document: <b>${docTitle}</b>.</p>
            <p style="color: #64748b; font-size: 13px; line-height: 1.6;">
                You are receiving this email as a copy for your reference and records only. <b>No signature or action is required from you.</b>
            </p>

            ${
              ccList
                ? `<p style="font-size: 13px; color: #475569; margin: 15px 0;"><b>CC:</b> ${ccList}</p>`
                : ""
            }
            
                ${
                  customMessage
                    ? `
            <div style="background-color: #f8fafc; border-left: 4px solid #0e9e8a; padding: 15px; margin: 20px 0;">
                <p style="margin: 0; font-style: italic; color: #475569;">"${customMessage}"</p>
                </div>
                `
                    : ""
                }

            <hr style="border: none; border-top: 1px solid #f1f5f9; margin: 25px 0 15px 0;" />
            <p style="font-size: 11px; color: #94a3b8; text-align: center; margin: 0;">This is an informational copy generated by DSMS. Do not reply to this email.</p>
        </div>
    `;
  },
  signatureProgress: (
    docTitle,
    signedCount,
    totalCount,
    remainingUsers,
    justSignedUser,
    docId,
  ) => `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #0e9e8a; margin: 0;">DSMS</h1>
            </div>
            <h2 style="color: #0e9e8a; margin-top: 0;">Signature Update</h2>
            <p style="color: #334155; font-size: 14px; margin: 8px 0;">Document Title: <b>${docTitle}</b></p>
            <p style="color: #334155; font-size: 14px; margin: 8px 0;"><b>${justSignedUser}</b> has just signed the document.</p>
            <p style="color: #334155; font-size: 14px; margin: 8px 0;">Progress: <b>${signedCount} out of ${totalCount}</b> people have signed.</p>
            <p style="color: #334155; font-size: 14px; margin: 8px 0;">Waiting for: <b>${remainingUsers.join(", ")}</b></p>
            <hr style="border: none; border-top: 1px solid #f1f5f9; margin: 20px 0 10px 0;" />
            <p style="font-size: 11px; color: #94a3b8; text-align: center; margin: 0;">This is an automated progress update notification generated by DSMS.</p>
        </div>
    `,
  documentCompleted: (docTitle, docId) => {
    const frontendUrl = process.env.FRONTEND_URL || 'https://dsms-web-app-bay.vercel.app';
    const targetUrl = `${frontendUrl}/documents`;

    return `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 25px;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #0e9e8a; margin: 0; font-size: 26px;">DSMS</h1>
                <p style="color: #64748b; font-size: 11px; margin: 4px 0 0 0; text-transform: uppercase; letter-spacing: 1px;">Digital Signature Management System</p>
            </div>

            <h2 style="color: #0e9e8a; margin-top: 20px; font-size: 18px;">✅ Document Completed</h2>
            
            <p style="color: #334155; font-size: 14px; line-height: 1.6; margin: 12px 0;">
                Great news! All participants have successfully reviewed and signed the document.
            </p>

            <div style="background-color: #f8fafc; border-left: 4px solid #0e9e8a; padding: 15px; margin: 18px 0; border-radius: 4px;">
                <p style="margin: 0 0 6px 0; font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: bold;">Document Title</p>
                <p style="margin: 0; font-size: 15px; font-weight: bold; color: #0f172a;">${docTitle}</p>
            </div>

            <p style="color: #475569; font-size: 13px; line-height: 1.6; margin: 12px 0;">
                The finalized and sealed PDF is now available. You can view or download the fully signed version directly from your documents dashboard.
            </p>

            <div style="text-align: center; margin: 30px 0;">
                <a href="${targetUrl}" style="background-color: #0e9e8a; color: white; padding: 12px 28px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; font-size: 14px;">View Document</a>
            </div>

            <hr style="border: none; border-top: 1px solid #f1f5f9; margin: 25px 0 15px 0;" />
            <p style="font-size: 11px; color: #94a3b8; text-align: center; margin: 0;">This is an automated completion notice generated by DSMS. Do not reply to this email.</p>
        </div>
    `;
  },
};

module.exports = { sendEmail, templates };
